// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIor6K-h5HM0Hsd2lTX3HRlE01nJF6F4',
    appId: '1:340389082213:android:3c7d916f27621c3d69c28c',
    messagingSenderId: '340389082213',
    projectId: 'handsfree-bef74',
    storageBucket: 'handsfree-bef74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhxSrx0bkYy8OPH7IbKhrjMOI8KRIuiAI',
    appId: '1:340389082213:ios:b177e28951b4012f69c28c',
    messagingSenderId: '340389082213',
    projectId: 'handsfree-bef74',
    storageBucket: 'handsfree-bef74.appspot.com',
    iosClientId: '340389082213-ftophm3ta2cdedfvapt6dll4dgank6i5.apps.googleusercontent.com',
    iosBundleId: 'com.umquartet02.handsfree',
  );
}
